### ISSUE TITLE
please make sample .env file in root

### ISSUE THREAD

**Issue by chatgpt9** [QASchoolUSA/Automated-Youtube-Channel-Final#2]
Hi,
please make sample .env file in root
& also if possible make dockerfile ...
waiting for your response
regards

**Comment by QASchoolUSA** [comment]
.env_sample file is added.

I'm not really proficient using Docker and I feel like you would face a few issues using Docker, cause script for uploading using "Login with GMAIL" and Google blocks access using headless mode for Puppeteer, so as workaround you might need to stick with actual non-headless Chrome. 

Correct me If I'm wrong, I can give contributor rights and you can add it yourself and test it out, if that's gonna work.

**Comment by QASchoolUSA** [comment]
I might have found a solution to make it work with Docker.
https://stackoverflow.com/questions/53942598/run-a-not-headless-chrome-on-a-docker-container

**Comment by chatgpt9** [comment]
one more question is playwright is required ?!

**Comment by chatgpt9** [comment]
after deployed using dockerfile get error below :

`Running script...
node:fs:1456
handleErrorFromBinding(ctx);
^
Error: ENOENT: no such file or directory, scandir '/app/videos/'
at Object.readdirSync (node:fs:1456:3)
at downloadingVideos (/app/tests/uploadVideo.js:13:21)
at uploadVideo (/app/tests/uploadVideo.js:38:31)
at Object.<anonymous> (/app/tests/uploadVideo.js:108:1)
at Module._compile (node:internal/modules/cjs/loader:1275:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
at Module.load (node:internal/modules/cjs/loader:1133:32)
at Module._load (node:internal/modules/cjs/loader:972:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
at node:internal/main/run_main_module:23:47 {
errno: -2,
syscall: 'scandir',
code: 'ENOENT',
path: '/app/videos/'
}
Node.js v19.8.1
(EE)
Fatal server error:
(EE) Server is already active for display 99
If this server is no longer running, remove /tmp/.X99-lock
and start again.
(EE)`

my dockerfile : 
https://github.com/chatgpt9/Automated-Youtube-Channel-Final/blob/main/Dockerfile

please make changes on main branch to autopilot python file can run hourly task of get videos from exist user list & auto publish on youtube.
waiting for your response

**Comment by QASchoolUSA** [comment]
> one more question is playwright is required ?!

At first, I started to implement that with Playwright, then switched to Puppeteer, so no, it' not required
